name: getx_skeleton
version: 1.0.0+1
publish_to: none
description: start your project in the fastest way
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  get: ^4.6.5 # for state management and context less stuff

  logger: ^1.4.0 # log events in clear way insted of (print)

  flutter_screenutil: ^5.8.4 # make app responsive

  dio: ^5.2.1+1 # for api requests
  pretty_dio_logger: ^1.3.1 # for dio api logging and debugging

  shared_preferences: ^2.2.0 # shared preferences persistence key value store

  firebase_core: ^2.14.0 # to initialize firebase services
  firebase_messaging: ^14.6.4 # fcm services
  awesome_notifications: ^0.7.4+1 # notifications services (will be used for fcm)

  flutter_launcher_icons: # change app icon
  change_app_package_name: # change package name
  rename_app: 1.0.0 # rename app

  flutter_svg: # display svg vectors

  flutter:
    sdk: flutter
  rive: ^0.13.9
  barcode_scan2: ^4.3.1
  dropdown_button2: ^2.3.9
  infinite_scroll_pagination: ^4.0.0
  loadmore: ^2.1.0

dev_dependencies:
  mockito:
  flutter_lints:

  integration_test:
    sdk: flutter

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/Fonts/
    - assets/icons/
    - assets/RiveAssets/
    - assets/shapes/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
